### PR TITLE
fix several problem in CardInfo

### LINKED ISSUE #9: fix several problems in CardInfo()
I wanted to use Card Info but this has some problem. Decision create list problem Card Info & resolve it.

1. exposed function has unexposed response.
2. fill some bank does not exist in bank list.

### PR DESCRIPTION
**Pull request by masihtehrani**
fix #9

### CODE REVIEW

**Comment by ali-master** [comment]
Hi @masihtehrani Jan,

Thanks for contributing to the Project. I appreciate it and hope to see more collaboration.

**Comment by masihtehrani** [comment]
> Hi @masihtehrani Jan,
> 
> Thanks for contributing to the Project. I appreciate it and hope to see more collaboration.

Your welcome, We had decision use this package in project but when start we knew it doesn't has exposed response. I try fix this problem know several problems and fix all problem. one another point this package does not have complete data of bank I added several bank data.
thank your good packages in several language programming. ;)

File: bank/bank.go [hunk 1]
```diff
@@ -1,55 +1,83 @@
...
+	"606256": "melal",
+	"505801": "kosar",
+	"507677": "noor",
 }
 
-type Card struct {
-	Number string
-}
-
-func (c *Card) CardInfo() response {
```
Comment (nimahkh) [inline bank/bank.go:16]: May I ask you please explain this? why we have remove pointer? when you use pointers your application will be faster, because you’ll avoid copying data around all the time. and our data is a constant

File: bank/bank.go [hunk 2]
```diff
@@ -1,55 +1,83 @@
...
 import (
+	"errors"
+	"regexp"
 	"strconv"
 )
 
-type response struct {
-	bankName string
-	isValid  bool
+var bankCode = map[string]string{
```
Comment (nimahkh) [inline bank/bank.go:9]: This map is duplicated, we have all the data in `bank_code.go`, may I ask you please explain it? Thanks

File: bank/bank.go (hunk 1 above)
Comment (masihtehrani) [reply bank/bank.go:16]: your implement with method & I implementation with function. your implementation with method is not faster than function! I just use function because it's shorter & easiest to use.

File: bank/bank.go (hunk 2 above)
Comment (masihtehrani) [reply bank/bank.go:9]: yes of course. but we have just two options map & slice. both of them has duplicate! but in map you can find key without use loop & it's faster than find with loop.

**Review by nimahkh — APPROVED** [review]

**Comment by ali-master** [comment]
@masihtehrani Welcome to the PersianTools contributors team.

@nimahkh Thanks Nima Joon for reviewing and merging the PR.
